EmptyList = []
n = int(input("\nEnter number of elements: "))
for i in range(0, n):
    elm = int(input())
    EmptyList.append(elm)

print()
print(EmptyList)
print()
EmptyList.append(15)
print(EmptyList)
print()
EmptyList.pop()
print(EmptyList)
print()
EmptyList.insert(3, 22)
print(EmptyList)
print()
EmptyList.remove(2)
print(EmptyList)
print()
EmptyList.sort()
print(EmptyList)
print()
EmptyList.clear()
print(EmptyList)